[package]
name = "workspace"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
cbc = "0.1.2"
ed25519-dalek = "2.2.0"
hkdf = "0.12.4"
hmac = "0.12.1"
rand = "0.8"
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.10.9"
x25519-dalek = "2.0.1"
